// Code generated by protoc-gen-go. DO NOT EDIT.
// source: communication.proto

package communication

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "github.com/lyft/protoc-gen-validate/validate"
import wtypes "wtypes"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// IP address.
type IP struct {
	Addr                 string   `protobuf:"bytes,1,opt,name=addr,proto3" json:"addr,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Port                 int32    `protobuf:"varint,3,opt,name=port,proto3" json:"port,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *IP) Reset()         { *m = IP{} }
func (m *IP) String() string { return proto.CompactTextString(m) }
func (*IP) ProtoMessage()    {}
func (*IP) Descriptor() ([]byte, []int) {
	return fileDescriptor_communication_1604fb66fc8b0873, []int{0}
}
func (m *IP) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IP.Unmarshal(m, b)
}
func (m *IP) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IP.Marshal(b, m, deterministic)
}
func (dst *IP) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IP.Merge(dst, src)
}
func (m *IP) XXX_Size() int {
	return xxx_messageInfo_IP.Size(m)
}
func (m *IP) XXX_DiscardUnknown() {
	xxx_messageInfo_IP.DiscardUnknown(m)
}

var xxx_messageInfo_IP proto.InternalMessageInfo

func (m *IP) GetAddr() string {
	if m != nil {
		return m.Addr
	}
	return ""
}

func (m *IP) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *IP) GetPort() int32 {
	if m != nil {
		return m.Port
	}
	return 0
}

// Greet request contains id, ip and message.
type GreetRequest struct {
	//
	// wtypes.Int64 id = 1 [(validate.rules).uint64.gt = 1000];
	// IP ip = 2 [(validate.rules).message.required = true];
	// string message = 3 [(validate.rules).string = {min_len: 0, max_len: 65535}];
	// // try Double
	// wtypes.Double num = 4 [(validate.rules).wdouble.gt = 10];
	Doublenum            *wtypes.Double `protobuf:"bytes,1,opt,name=doublenum,proto3" json:"doublenum,omitempty"`
	Floatnum             *wtypes.Float  `protobuf:"bytes,2,opt,name=floatnum,proto3" json:"floatnum,omitempty"`
	Int64Num             *wtypes.Int64  `protobuf:"bytes,3,opt,name=int64num,proto3" json:"int64num,omitempty"`
	Uint64Num            *wtypes.UInt64 `protobuf:"bytes,4,opt,name=uint64num,proto3" json:"uint64num,omitempty"`
	Int32Num             *wtypes.Int32  `protobuf:"bytes,5,opt,name=int32num,proto3" json:"int32num,omitempty"`
	Uint32Num            *wtypes.UInt32 `protobuf:"bytes,6,opt,name=uint32num,proto3" json:"uint32num,omitempty"`
	Str                  *wtypes.String `protobuf:"bytes,7,opt,name=str,proto3" json:"str,omitempty"`
	Bo                   *wtypes.Bool   `protobuf:"bytes,8,opt,name=bo,proto3" json:"bo,omitempty"`
	B                    *wtypes.Bytes  `protobuf:"bytes,9,opt,name=b,proto3" json:"b,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *GreetRequest) Reset()         { *m = GreetRequest{} }
func (m *GreetRequest) String() string { return proto.CompactTextString(m) }
func (*GreetRequest) ProtoMessage()    {}
func (*GreetRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_communication_1604fb66fc8b0873, []int{1}
}
func (m *GreetRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GreetRequest.Unmarshal(m, b)
}
func (m *GreetRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GreetRequest.Marshal(b, m, deterministic)
}
func (dst *GreetRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GreetRequest.Merge(dst, src)
}
func (m *GreetRequest) XXX_Size() int {
	return xxx_messageInfo_GreetRequest.Size(m)
}
func (m *GreetRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GreetRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GreetRequest proto.InternalMessageInfo

func (m *GreetRequest) GetDoublenum() *wtypes.Double {
	if m != nil {
		return m.Doublenum
	}
	return nil
}

func (m *GreetRequest) GetFloatnum() *wtypes.Float {
	if m != nil {
		return m.Floatnum
	}
	return nil
}

func (m *GreetRequest) GetInt64Num() *wtypes.Int64 {
	if m != nil {
		return m.Int64Num
	}
	return nil
}

func (m *GreetRequest) GetUint64Num() *wtypes.UInt64 {
	if m != nil {
		return m.Uint64Num
	}
	return nil
}

func (m *GreetRequest) GetInt32Num() *wtypes.Int32 {
	if m != nil {
		return m.Int32Num
	}
	return nil
}

func (m *GreetRequest) GetUint32Num() *wtypes.UInt32 {
	if m != nil {
		return m.Uint32Num
	}
	return nil
}

func (m *GreetRequest) GetStr() *wtypes.String {
	if m != nil {
		return m.Str
	}
	return nil
}

func (m *GreetRequest) GetBo() *wtypes.Bool {
	if m != nil {
		return m.Bo
	}
	return nil
}

func (m *GreetRequest) GetB() *wtypes.Bytes {
	if m != nil {
		return m.B
	}
	return nil
}

// Greet reply contains message and ip.
type GreetReply struct {
	Message              string   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Ip                   *IP      `protobuf:"bytes,2,opt,name=ip,proto3" json:"ip,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GreetReply) Reset()         { *m = GreetReply{} }
func (m *GreetReply) String() string { return proto.CompactTextString(m) }
func (*GreetReply) ProtoMessage()    {}
func (*GreetReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_communication_1604fb66fc8b0873, []int{2}
}
func (m *GreetReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GreetReply.Unmarshal(m, b)
}
func (m *GreetReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GreetReply.Marshal(b, m, deterministic)
}
func (dst *GreetReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GreetReply.Merge(dst, src)
}
func (m *GreetReply) XXX_Size() int {
	return xxx_messageInfo_GreetReply.Size(m)
}
func (m *GreetReply) XXX_DiscardUnknown() {
	xxx_messageInfo_GreetReply.DiscardUnknown(m)
}

var xxx_messageInfo_GreetReply proto.InternalMessageInfo

func (m *GreetReply) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *GreetReply) GetIp() *IP {
	if m != nil {
		return m.Ip
	}
	return nil
}

// Email login.
type AccessRequest struct {
	Ip                   *IP                  `protobuf:"bytes,1,opt,name=ip,proto3" json:"ip,omitempty"`
	IsCN                 bool                 `protobuf:"varint,2,opt,name=isCN,proto3" json:"isCN,omitempty"`
	Email                *AccessRequest_Email `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *AccessRequest) Reset()         { *m = AccessRequest{} }
func (m *AccessRequest) String() string { return proto.CompactTextString(m) }
func (*AccessRequest) ProtoMessage()    {}
func (*AccessRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_communication_1604fb66fc8b0873, []int{3}
}
func (m *AccessRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AccessRequest.Unmarshal(m, b)
}
func (m *AccessRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AccessRequest.Marshal(b, m, deterministic)
}
func (dst *AccessRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AccessRequest.Merge(dst, src)
}
func (m *AccessRequest) XXX_Size() int {
	return xxx_messageInfo_AccessRequest.Size(m)
}
func (m *AccessRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AccessRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AccessRequest proto.InternalMessageInfo

func (m *AccessRequest) GetIp() *IP {
	if m != nil {
		return m.Ip
	}
	return nil
}

func (m *AccessRequest) GetIsCN() bool {
	if m != nil {
		return m.IsCN
	}
	return false
}

func (m *AccessRequest) GetEmail() *AccessRequest_Email {
	if m != nil {
		return m.Email
	}
	return nil
}

type AccessRequest_Email struct {
	Email                string   `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Pwd                  string   `protobuf:"bytes,2,opt,name=pwd,proto3" json:"pwd,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AccessRequest_Email) Reset()         { *m = AccessRequest_Email{} }
func (m *AccessRequest_Email) String() string { return proto.CompactTextString(m) }
func (*AccessRequest_Email) ProtoMessage()    {}
func (*AccessRequest_Email) Descriptor() ([]byte, []int) {
	return fileDescriptor_communication_1604fb66fc8b0873, []int{3, 0}
}
func (m *AccessRequest_Email) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AccessRequest_Email.Unmarshal(m, b)
}
func (m *AccessRequest_Email) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AccessRequest_Email.Marshal(b, m, deterministic)
}
func (dst *AccessRequest_Email) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AccessRequest_Email.Merge(dst, src)
}
func (m *AccessRequest_Email) XXX_Size() int {
	return xxx_messageInfo_AccessRequest_Email.Size(m)
}
func (m *AccessRequest_Email) XXX_DiscardUnknown() {
	xxx_messageInfo_AccessRequest_Email.DiscardUnknown(m)
}

var xxx_messageInfo_AccessRequest_Email proto.InternalMessageInfo

func (m *AccessRequest_Email) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *AccessRequest_Email) GetPwd() string {
	if m != nil {
		return m.Pwd
	}
	return ""
}

// The reply to client access.
type AccessReply struct {
	Ip                   *IP      `protobuf:"bytes,1,opt,name=ip,proto3" json:"ip,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AccessReply) Reset()         { *m = AccessReply{} }
func (m *AccessReply) String() string { return proto.CompactTextString(m) }
func (*AccessReply) ProtoMessage()    {}
func (*AccessReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_communication_1604fb66fc8b0873, []int{4}
}
func (m *AccessReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AccessReply.Unmarshal(m, b)
}
func (m *AccessReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AccessReply.Marshal(b, m, deterministic)
}
func (dst *AccessReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AccessReply.Merge(dst, src)
}
func (m *AccessReply) XXX_Size() int {
	return xxx_messageInfo_AccessReply.Size(m)
}
func (m *AccessReply) XXX_DiscardUnknown() {
	xxx_messageInfo_AccessReply.DiscardUnknown(m)
}

var xxx_messageInfo_AccessReply proto.InternalMessageInfo

func (m *AccessReply) GetIp() *IP {
	if m != nil {
		return m.Ip
	}
	return nil
}

func (m *AccessReply) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func init() {
	proto.RegisterType((*IP)(nil), "communication.IP")
	proto.RegisterType((*GreetRequest)(nil), "communication.GreetRequest")
	proto.RegisterType((*GreetReply)(nil), "communication.GreetReply")
	proto.RegisterType((*AccessRequest)(nil), "communication.AccessRequest")
	proto.RegisterType((*AccessRequest_Email)(nil), "communication.AccessRequest.Email")
	proto.RegisterType((*AccessReply)(nil), "communication.AccessReply")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// CommunicationClient is the client API for Communication service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type CommunicationClient interface {
	// Sends a greeting.
	Greet(ctx context.Context, in *GreetRequest, opts ...grpc.CallOption) (*GreetReply, error)
	// Login email.
	Login(ctx context.Context, in *AccessRequest, opts ...grpc.CallOption) (*AccessReply, error)
}

type communicationClient struct {
	cc *grpc.ClientConn
}

func NewCommunicationClient(cc *grpc.ClientConn) CommunicationClient {
	return &communicationClient{cc}
}

func (c *communicationClient) Greet(ctx context.Context, in *GreetRequest, opts ...grpc.CallOption) (*GreetReply, error) {
	out := new(GreetReply)
	err := c.cc.Invoke(ctx, "/communication.Communication/Greet", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *communicationClient) Login(ctx context.Context, in *AccessRequest, opts ...grpc.CallOption) (*AccessReply, error) {
	out := new(AccessReply)
	err := c.cc.Invoke(ctx, "/communication.Communication/Login", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CommunicationServer is the server API for Communication service.
type CommunicationServer interface {
	// Sends a greeting.
	Greet(context.Context, *GreetRequest) (*GreetReply, error)
	// Login email.
	Login(context.Context, *AccessRequest) (*AccessReply, error)
}

func RegisterCommunicationServer(s *grpc.Server, srv CommunicationServer) {
	s.RegisterService(&_Communication_serviceDesc, srv)
}

func _Communication_Greet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GreetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CommunicationServer).Greet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/communication.Communication/Greet",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CommunicationServer).Greet(ctx, req.(*GreetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Communication_Login_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AccessRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CommunicationServer).Login(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/communication.Communication/Login",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CommunicationServer).Login(ctx, req.(*AccessRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Communication_serviceDesc = grpc.ServiceDesc{
	ServiceName: "communication.Communication",
	HandlerType: (*CommunicationServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Greet",
			Handler:    _Communication_Greet_Handler,
		},
		{
			MethodName: "Login",
			Handler:    _Communication_Login_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "communication.proto",
}

func init() { proto.RegisterFile("communication.proto", fileDescriptor_communication_1604fb66fc8b0873) }

var fileDescriptor_communication_1604fb66fc8b0873 = []byte{
	// 630 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x94, 0x31, 0x6f, 0xd3, 0x4e,
	0x18, 0xc6, 0x73, 0x67, 0x3b, 0xb5, 0xdf, 0x36, 0x55, 0x7a, 0xff, 0xc5, 0x7f, 0x43, 0x45, 0xb0,
	0x40, 0x44, 0x40, 0x13, 0x29, 0x05, 0x54, 0x89, 0x01, 0xea, 0x16, 0xaa, 0x4a, 0x08, 0x55, 0x87,
	0xd8, 0xb1, 0x93, 0x6b, 0x62, 0xc9, 0xf6, 0x19, 0xfb, 0x42, 0x95, 0x8d, 0x99, 0x2f, 0xc0, 0x77,
	0xe9, 0x84, 0x18, 0x19, 0x19, 0xd9, 0x60, 0x83, 0x09, 0x31, 0xb2, 0x14, 0xdd, 0xd9, 0x4e, 0xe3,
	0x16, 0x2a, 0xc8, 0x10, 0x59, 0xef, 0xf3, 0xfc, 0xde, 0xe7, 0x7c, 0xef, 0x9d, 0xe1, 0xbf, 0x21,
	0x8f, 0xe3, 0x69, 0x12, 0x0e, 0x7d, 0x11, 0xf2, 0xa4, 0x97, 0x66, 0x5c, 0x70, 0xd2, 0xaa, 0x15,
	0x9d, 0xfb, 0xe3, 0x50, 0x4c, 0xa6, 0x41, 0x6f, 0xc8, 0xe3, 0x7e, 0x34, 0x3b, 0x14, 0x7d, 0xe5,
	0x1a, 0x6e, 0x8c, 0x59, 0xb2, 0xf1, 0xca, 0x8f, 0xc2, 0x91, 0x2f, 0x58, 0xff, 0xdc, 0x43, 0xd1,
	0xcb, 0x21, 0x47, 0x62, 0x96, 0xb2, 0xbc, 0xaf, 0xfe, 0x8b, 0x9a, 0x7b, 0x08, 0x78, 0xff, 0x80,
	0xac, 0x83, 0xee, 0x8f, 0x46, 0x99, 0x8d, 0x3a, 0xa8, 0x6b, 0x79, 0xd6, 0xf1, 0xd7, 0x77, 0x9a,
	0x9e, 0xe1, 0x14, 0x51, 0x55, 0x96, 0x72, 0xe2, 0xc7, 0xcc, 0xc6, 0x35, 0x79, 0x82, 0xa8, 0x2a,
	0x13, 0x17, 0xf4, 0x94, 0x67, 0xc2, 0xd6, 0x3a, 0xa8, 0x6b, 0x78, 0xab, 0x52, 0xb6, 0x9c, 0x25,
	0xfb, 0xe4, 0x44, 0xeb, 0xbe, 0x36, 0xa9, 0xd2, 0xdc, 0xef, 0x1a, 0xac, 0xec, 0x65, 0x8c, 0x09,
	0xca, 0x5e, 0x4e, 0x59, 0x2e, 0xc8, 0x03, 0xb0, 0x46, 0x7c, 0x1a, 0x44, 0x2c, 0x99, 0xc6, 0x2a,
	0x77, 0x79, 0xb0, 0xda, 0x2b, 0x16, 0xd8, 0xdb, 0x55, 0x82, 0xb7, 0x26, 0x3b, 0xad, 0x1c, 0x23,
	0xeb, 0x6a, 0x43, 0xfd, 0xae, 0x3d, 0xa4, 0xa7, 0x0c, 0xd9, 0x02, 0xf3, 0x30, 0xe2, 0xbe, 0x90,
	0x3c, 0x56, 0x7c, 0xab, 0xe2, 0x1f, 0xcb, 0xba, 0xd7, 0x92, 0xb8, 0xf9, 0x1e, 0x19, 0xd7, 0x1b,
	0x8d, 0xce, 0x36, 0x9d, 0xbb, 0xc9, 0x5d, 0x30, 0xc3, 0x44, 0xdc, 0xbb, 0x23, 0x49, 0xad, 0x4e,
	0xee, 0xcb, 0xba, 0x07, 0x92, 0x34, 0x3e, 0x20, 0xdc, 0x01, 0x3a, 0xb7, 0x92, 0x2d, 0xb0, 0xa6,
	0x73, 0x4e, 0xaf, 0xaf, 0xf8, 0xf9, 0x22, 0xf8, 0x51, 0x81, 0xa7, 0xe6, 0x32, 0x70, 0x73, 0x20,
	0x41, 0xe3, 0x5c, 0xe0, 0xe6, 0xa0, 0xe4, 0x3e, 0xcd, 0x03, 0x95, 0xb5, 0x0a, 0x2c, 0xb8, 0xe6,
	0xf9, 0xc0, 0x39, 0xf8, 0xe5, 0x34, 0xb0, 0x20, 0x6f, 0x83, 0x96, 0x8b, 0xcc, 0x5e, 0xaa, 0x33,
	0xcf, 0x44, 0x16, 0x26, 0xe3, 0x92, 0xf9, 0x81, 0x70, 0x1b, 0x53, 0x69, 0x23, 0x5d, 0xc0, 0x01,
	0xb7, 0x4d, 0x65, 0x5e, 0xa9, 0xcc, 0x1e, 0xe7, 0x51, 0x69, 0xfd, 0x86, 0xb0, 0x89, 0x28, 0x0e,
	0x38, 0xb9, 0x05, 0x28, 0xb0, 0xad, 0xfa, 0x1b, 0x78, 0x33, 0xc1, 0xf2, 0x72, 0xea, 0x3f, 0x51,
	0xf3, 0xa6, 0x3e, 0xf1, 0x27, 0x3e, 0x45, 0x81, 0x3b, 0x02, 0x28, 0x27, 0x9e, 0x46, 0x33, 0x72,
	0x03, 0x96, 0x62, 0x96, 0xe7, 0xfe, 0x98, 0x95, 0xa7, 0xac, 0x18, 0x4f, 0xd6, 0x6c, 0x37, 0xe4,
	0x49, 0xa1, 0x95, 0x4a, 0x36, 0x00, 0x87, 0x69, 0x39, 0xd1, 0xb5, 0x5e, 0xfd, 0x4e, 0xec, 0x1f,
	0x94, 0x4b, 0x7a, 0x83, 0x70, 0x1b, 0x51, 0x1c, 0xa6, 0xee, 0x67, 0x04, 0xad, 0xed, 0xe1, 0x90,
	0xe5, 0x79, 0x75, 0xb2, 0x8a, 0x06, 0xe8, 0x2f, 0x1b, 0x10, 0x02, 0x7a, 0x98, 0xef, 0x3c, 0x55,
	0x89, 0x26, 0x55, 0xcf, 0x64, 0x17, 0x0c, 0x16, 0xfb, 0x61, 0x54, 0x1e, 0x0f, 0xf7, 0x4c, 0x97,
	0x5a, 0x5e, 0xef, 0x91, 0x74, 0xd6, 0xda, 0x16, 0xb0, 0xb3, 0x07, 0x86, 0xd2, 0xc8, 0x95, 0xaa,
	0x5d, 0xfd, 0x7e, 0xbd, 0xa8, 0x9c, 0x64, 0x1d, 0xb4, 0xf4, 0x68, 0x54, 0xde, 0xaf, 0x65, 0x29,
	0x37, 0x33, 0xbd, 0xdd, 0xb0, 0xdb, 0x54, 0xd6, 0x5d, 0x06, 0xcb, 0x55, 0xa4, 0xdc, 0xca, 0x7f,
	0x7c, 0xc1, 0x85, 0x9d, 0xc7, 0x17, 0xed, 0xfc, 0xe0, 0x2d, 0x82, 0xd6, 0xce, 0x62, 0x37, 0xb2,
	0x0d, 0x86, 0x1a, 0x21, 0xb9, 0x74, 0x26, 0x66, 0xf1, 0x2a, 0x3b, 0xff, 0xff, 0x5e, 0x4c, 0xa3,
	0x99, 0xdb, 0x20, 0x3b, 0x60, 0x3c, 0xe1, 0xe3, 0x30, 0x21, 0x97, 0x2f, 0xda, 0x44, 0xc7, 0xf9,
	0x83, 0xaa, 0x9a, 0x04, 0x4d, 0xf5, 0xb1, 0xda, 0xfc, 0x15, 0x00, 0x00, 0xff, 0xff, 0x41, 0xa8,
	0x17, 0x18, 0x23, 0x05, 0x00, 0x00,
}
